DJ_DIR: /home/domjudge/domjudge-checkout

DJ_FORCE_UPDATE: false

DOMSERVER_URL: https://localhost

PHP_FPM_MAX_CHILDREN: 5

DOMSERVER_SSL_CERT: /etc/ssl/certs/localhost.crt
DOMSERVER_SSL_KEY: /etc/ssl/private/localhost.key
