---
# Tasks to build DOMjudge

- name: add the restapi secret file
  template:
    src: restapi.secret.j2
    dest: "{{ DJ_DIR }}/etc/restapi.secret"
    owner: domjudge
    group: domjudge
    mode: 0600

- name: run inplace-conf
  become: true
  become_user: domjudge
  command: make inplace-conf CONFIGURE_FLAGS='--disable-doc-build --with-baseurl={{ DOMSERVER }}/'
  register: dj_configured
  args:
    chdir: "{{ DJ_DIR }}"
    creates: "{{ DJ_DIR }}/paths.mk"

- name: check if domjudge is built
  stat: path="{{ DJ_DIR }}/judge/judgedaemon"
  register: judgedaemon_binary

- name: build domjudge
  become: true
  become_user: domjudge
  command: make inplace-install
  args:
    chdir: "{{ DJ_DIR }}"
  notify: fix permissions on domjudge inplace-install
  when: (git_working_copy is defined and git_working_copy.changed) or dj_configured.changed or not judgedaemon_binary.stat.exists

- name: copy domjudge-sudoers file
  copy:
    remote_src: true
    src: "{{ DJ_DIR }}/etc/sudoers-domjudge"
    dest: /etc/sudoers.d/domjudge
    mode: 0440
    owner: root
    group: root

- name: configure domjudge logging
  copy:
    src: rsyslog.domjudge.conf
    dest: /etc/rsyslog.d/domjudge.conf
  notify: restart rsyslog

- name: configure domjudge logrotate
  copy:
    src: logrotate.domjudge
    dest: /etc/logrotate.d/domjudge
