---
# Define here handlers associated to this role.

- name: fix permissions on domjudge inplace-install
  shell: make -C {{DJ_DIR}} inplace-postinstall-permissions

- name: restart rsyslog
  service: name=rsyslog enabled=true state=restarted
