---
# These tasks configure clusterssh

- name: install clusterssh package
  apt:
    state: present
    pkg:
      - clusterssh

- name: create clusterssh 'all' config group
  become: true
  become_user: domjudge
  lineinfile:
    dest: /home/domjudge/.clusterssh/clusters
    regexp: '^all'
    line: "all {{ groups['all'] | join(' ') }}"
    create: true

- name: create clusterssh config groups
  become: true
  become_user: domjudge
  lineinfile:
    dest: /home/domjudge/.clusterssh/clusters
    regexp: '^{{ item }}s'
    line: "{{ item }}s {{ groups[item] | join(' ') }}"
    create: true
  loop:
    - domserver
    - judgehost
    - admin
