REMOVED_PACKAGES:
  - apport
  - ntp

INSTALLED_PACKAGES:
  - yarnpkg
  - ack
  - acl
  - apache2-utils
  - autoconf
  - automake
  - bat
  - bats
  - bsdmainutils
  - composer
  - curl
  - debootstrap
  - default-jdk-headless
  - efibootmgr
  - etckeeper
  - fontconfig
  - g++
  - gcc
  - git
  - git-gui
  - gitk
  - htop
  - btop
  - httpie
  - jq
  - latexmk
  - libcgroup-dev
  - libcurl4-gnutls-dev
  - libjsoncpp-dev
  - libmagic-dev
  - make
  - ncdu
  - php-cli
  - php-curl
  - php-gd
  - php-intl
  - php-json
  - php-mbstring
  - php-mysql
  - php-xml
  - php-zip
  - php-bcmath
  - pv
  - python3-sphinx
  - python3-sphinx-rtd-theme
  - python3-yaml
  - rst2pdf
  - screen
  - tig
  - tree
  - unzip
  - zip

GRAPHICAL_INSTALLED_PACKAGES:
  - dconf-cli
  - python3-psutil
  - gnome-terminal
  - fonts-noto-color-emoji
