---
# These tasks perform fixes used on the ICPC image to the base system.

- name: add NTP servers
  lineinfile:
    dest: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: "NTP=10.3.3.208 10.3.3.209"
  notify: restart systemd timesyncd
  when: WF_RESTRICTED_NETWORK

- name: remove source line from interfaces
  lineinfile:
    dest: /etc/network/interfaces
    regexp: '^source-'
    state: absent

- name: Re-order PXEboot
  shell: efibootmgr -o {{ EFI_ORDER }}
  when: EFI_ORDER is defined

- name: disable mumble,selfie services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - mumble-server
    - selfie
