---
# These tasks create a domjudge system account and fix sudo/autologin

- name: create domjudge user
  user:
    name: domjudge
    shell: /bin/bash
    groups: sudo
    password: "{{DJ_SHELL_USER_PW | default(omit)}}"

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: configure git user
  ini_file:
    dest: /home/domjudge/.gitconfig
    section: user
    option: "{{item.name}}"
    value: "{{item.value}}"
    owner: domjudge
    group: domjudge
  with_items:
    - { name: 'email', value: 'team@domjudge.org' }
    - { name: 'name', value: 'DOMjudge team' }

- name: configure git to rebase on pull
  ini_file:
    dest: /home/domjudge/.gitconfig
    section: branch
    option: "autosetuprebase"
    value: "remote"
    owner: domjudge
    group: domjudge

- name: enable GDM autologin
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: 'AutomaticLoginEnable'
    line: 'AutomaticLoginEnable=true'
    create: yes
  notify: restart gdm

- name: Automatically login domjudge user
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: 'AutomaticLogin'
    line: 'AutomaticLogin=domjudge'
  notify: restart gdm

- name: make sure autostart directory exists
  file: dest=/home/domjudge/.config/autostart state=directory owner=domjudge group=domjudge
