---
# These tasks install domlogo

- name: install python3 modules for domlogo
  apt:
    state: present
    pkg:
      - python3-tk

- name: install domlogo
  copy:
    src: domlogo.py
    dest: "{{DJ_DIR}}"
    owner: domjudge
    group: domjudge
    mode: 0755

- name: install domlogo env
  synchronize:
    src: lib
    dest: /home/domjudge/.local/
    owner: false
    use_ssh_args: true

- name: install domlogo images
  synchronize:
    src: images
    dest: "{{DJ_DIR}}"
    owner: false
    use_ssh_args: true

- name: add autostart shortcuts
  template:
    src: domjudgelogo.desktop.j2
    dest: /home/domjudge/.config/autostart/domjudgelogo.desktop
    owner: domjudge
    group: domjudge
    mode: 0755
