---
# This task configures packaging and installs various system utilities

- name: replace pc2.ecs.baylor.edu by packages in apt sources
  replace:
    dest: "/etc/apt/{{ item }}"
    regexp: 'pc2\.ecs\.baylor\.edu'
    replace: 'packages'
  loop:
    - sources.list
    - sources.list.d/microsoft.list
    - sources.list.d/mono.list
    - sources.list.d/vscode.list
    - sources.list.d/pypy-ubuntu-ppa-buster.list
  notify: run apt update
  when: WF_RESTRICTED_NETWORK

- name: add packages to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '^10\.3\.3\.209'
    line: "10.3.3.209 packages"
  notify: run apt update
  when: WF_RESTRICTED_NETWORK

- name: check for dpkg architecture i386
  command: dpkg --print-foreign-architectures
  register: dpkg_architectures
  changed_when: false

- name: remove unused dpkg architecture i386
  command: dpkg --remove-architecture i386
  notify: run apt update
  when: dpkg_architectures.stdout.find('i386') != -1

- name: remove pycharm repo
  replace:
    dest: /etc/apt/sources.list
    regexp: '^([^#].*pycharm.*)$'
    replace: '# \1'
  notify: run apt update

- name: flush handlers
  meta: flush_handlers

- name: remove some packages
  apt:
    state: absent
    pkg:
      - apport
      - ntp

- name: install common required/useful packages
  apt:
    state: present
    pkg:
      - ack
      - git
      - htop
      - httpie
      - ncdu
      - pv
      - screen
      - autoconf
      - automake
      - efibootmgr
      - curl
      - gcc
      - g++
      - default-jdk-headless
      - make
      - zip
      - unzip
      - php-cli
      - php-gd
      - php-curl
      - php-mysql
      - php-json
      - php-xml
      - php-zip
      - php-mbstring
      - php-intl
      - bsdmainutils
      - libcgroup-dev
      - libcurl4-gnutls-dev
      - libjsoncpp-dev
      - libmagic-dev
      - debootstrap
      - texlive-latex-recommended
      - texlive-latex-extra
      - apache2-utils
      - tig
      - bat
      - jq
      - python3-sphinx
      - autoconf
      - automake
      - bats
      - python3-sphinx
      - python3-sphinx-rtd-theme
      - rst2pdf
      - fontconfig
      - python3-yaml
      - latexmk
      - acl

- name: Check if composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_file

- name: Download Composer Installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /root/composer-setup.php
  when: not composer_file.stat.exists

- name: Install composer
  command: php /root/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  when: not composer_file.stat.exists

- name: install local DEB packages
  include: install-local-package.yml
  with_fileglob:
    - install-{{ host_type }}/*.deb
